#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Rebecca Consterdine 

# Short bio or description (displayed in the header)
description: History graduate, well intentioned and prone to overthinking. 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://scontent-lht6-1.xx.fbcdn.net/v/t1.0-9/p960x960/111218010_971199046660105_7499021786335841971_o.jpg?_nc_cat=111&_nc_sid=85a577&_nc_ohc=Z7MlGJ5kT1AAX_76eEM&_nc_ht=scontent-lht6-1.xx&_nc_tp=6&oh=38b8d15236bdb9e0d67c742dc6356308&oe=5F3C91B1https://scontent-lht6-1.xx.fbcdn.net/v/t1.0-9/p960x960/111218010_971199046660105_7499021786335841971_o.jpg?_nc_cat=111&_nc_sid=85a577&_nc_ohc=Z7MlGJ5kT1AAX_76eEM&_nc_ht=scontent-lht6-1.xx&_nc_tp=6&oh=38b8d15236bdb9e0d67c742dc6356308&oe=5F3C91B1

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: rebeccaconsterdine@gmail.com
  facebook:
  flickr:
  github: 
  instagram: rconsterdine
  linkedin:
  goodreads: https://www.goodreads.com/user/show/89092146
  rss: # just type anything here for a working RSS icon
  twitter: 
  youtube: # channel/<your_long_string> or user/<user-name>


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-minimal